# Generated by Django 5.1.3 on 2024-12-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='customers',
            unique_together={('name', 'email')},
        ),
    ]
