# Generated by Django 5.1.3 on 2024-12-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0007_bill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bill',
            new_name='bills',
        ),
    ]
