# Generated by Django 5.1.3 on 2024-12-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0009_alter_bills_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bills',
            table='bills_bill',
        ),
    ]
